sudo: required
services:
  - docker

before_install:
  - docker build -t lokmanick/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lokmanick/react-test npm test -- --coverage

after_success:
  - docker build -t lokmanick/multi-client ./client
  - docker build -t lokamnick/multi-nginx ./nginx
  - docker build -t lokmanick/multi-server ./server
  - docker build -t lokmanick/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take these images and push it to docker-hub
  - docker push lokmanick/multi-client
  - docker push lokmanick/multi-nginx
  - docker push lokmanick/multi-server
  - docker push lokmanick/multi-worker
